# Argo Rollout example for canary deployment testing
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-app-rollout
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
        - setWeight: 40
        - pause: {duration: 10s}
        - setWeight: 60
        - pause: {duration: 10s}
        - setWeight: 80
        - pause: {duration: 10s}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: test-app-rollout
  template:
    metadata:
      labels:
        app: test-app-rollout
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
