apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source: local git repo (after pushing) or directory
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
    # For our custom envoy app, we'd use:
    # repoURL: <your-git-repo>
    # path: apps/envoy

  destination:
    server: https://kubernetes.default.svc
    namespace: envoy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
