apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mattconzen/argo-testing.git
    targetRevision: HEAD
    path: apps/envoy

  destination:
    server: https://kubernetes.default.svc
    namespace: envoy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
